[variables]
NIXPACKS_NODE_VERSION = "22.11.0"
NIXPACKS_NPM_VERSION = "10"

[phases.setup]
aptPkgs = ["python3", "make", "g++"]

[start]
cmd = "node --disable-warning=DEP0040 --import tsx dist-server/server/entrypoint.js"
